# Install script for directory: C:/GitRepo/DX11_project/bullet-2.82-r2704/Demos

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/BULLET_PHYSICS")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/DX11ClothDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/HelloWorld/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/MultiThreadedDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/OpenCLClothDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/OpenGL/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/AllBulletDemos/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/CcdPhysicsDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/BulletXmlImportDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConstraintDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/SliderConstraintDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/GenericJointDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/Raytracer/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/RagdollDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ForkLiftDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/BasicDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/RollingFrictionDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/RaytestDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/VoronoiFractureDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/GyroscopicDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/FractureDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/Box2dDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/BspDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/MovingConcaveDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/VehicleDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/CharacterDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/SoftDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/SimplexDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/DynamicControlDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConvexHullDistance/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/DoublePrecisionDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConcaveDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/CollisionDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ContinuousConvexCollision/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/GjkConvexCastDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/MultiMaterialDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/SerializeDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/InternalEdgeDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/Benchmarks/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/ThreadingDemo/cmake_install.cmake")
  INCLUDE("C:/GitRepo/DX11_project/PwAG/BulletBuild/Demos/VectorAdd_OpenCL/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

